package com.example.mviimageeditor.utils

const val BASE_URL_API ="https://api.unsplash.com/"
const val BASE_URL = "https://unsplash.com/"
const val CONTENT_TYPE = "Content-Type"
const val RETROFIT = "Retrofit"
const val RETROFIT_AUTHORIZE = "Retrofit_Authorize"
const val ACCEPT = "Accept"
const val ACCEPT_LANGUAGE = "Accept-Language"
const val AUTHORIZATION = "Authorization"
const val PREF_ACCESS_TOKEN = "PREF_ACCESS_TOKEN"
const val CLIENT_ID = "K3hBadFpyF5VgNn4-n6dv116IEHWHtkfF-Mg5aRoryc"
const val ACCESS_KEY = "K3hBadFpyF5VgNn4-n6dv116IEHWHtkfF-Mg5aRoryc"
const val SECRET_KEY = "o8nq8WJ_l0wGgUYaAoCxgVK5oMcXFcUSOiuaYK4vjGU"
const val REDIRECT_URI = "urn:ietf:wg:oauth:2.0:oob"
const val RESPONSE_TYPE = "code"
const val SCOPE = "public+read_user+write_likes"
const val PAGE = "page"
const val COLLECTION_ENDPOINT = "collections"
const val HOME_INDEX = 0
const val SEARCH_INDEX = 1
const val CREATE_INDEX = 2
const val FAVORITE_INDEX = 3
const val URL = "URL"
const val FILE_TITLE = "Instagram Image"
const val QUERY_SEARCH = "query"
const val ALL = "all"
const val PHOTO_SEARCH_ENDPOINT = "search/photos"
const val AUTHORIZE_ENDPOINT = "oauth/token"
const val PER_PAGE = "per_page"
const val DEFAULT_PROGRESS_VALUE = 10
const val RANGE_CONTRAST_AND_BRIGHTNESS = 10f
const val SIGN_OF_AUTHORIZE = "authorize/native?code"
const val AUTHORIZE_DATA = "AUTHORIZE_DATA"
const val DEFAULT_EMOJI_SIZE = 48f
const val DATABASE_NAME = "imageEditor_database"
const val ID = "id"
const val NAME = "name"
